// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/recommendation/v1/recommendation.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRecommendedProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendedProductsRequest) Reset() {
	*x = GetRecommendedProductsRequest{}
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendedProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendedProductsRequest) ProtoMessage() {}

func (x *GetRecommendedProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendedProductsRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendedProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{0}
}

func (x *GetRecommendedProductsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRecommendedProductsRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetRecommendedProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendedProductsResponse) Reset() {
	*x = GetRecommendedProductsResponse{}
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendedProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendedProductsResponse) ProtoMessage() {}

func (x *GetRecommendedProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendedProductsResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendedProductsResponse) Descriptor() ([]byte, []int) {
	return file_api_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{1}
}

func (x *GetRecommendedProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_api_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{2}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

var File_api_recommendation_v1_recommendation_proto protoreflect.FileDescriptor

const file_api_recommendation_v1_recommendation_proto_rawDesc = "" +
	"\n" +
	"*api/recommendation/v1/recommendation.proto\x12\x11recommendation.v1\"N\n" +
	"\x1dGetRecommendedProductsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"X\n" +
	"\x1eGetRecommendedProductsResponse\x126\n" +
	"\bproducts\x18\x01 \x03(\v2\x1a.recommendation.v1.ProductR\bproducts\"\x82\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl2\x96\x01\n" +
	"\x15RecommendationService\x12}\n" +
	"\x16GetRecommendedProducts\x120.recommendation.v1.GetRecommendedProductsRequest\x1a1.recommendation.v1.GetRecommendedProductsResponseB$Z\"ecommerce/api/recommendation/v1;v1b\x06proto3"

var (
	file_api_recommendation_v1_recommendation_proto_rawDescOnce sync.Once
	file_api_recommendation_v1_recommendation_proto_rawDescData []byte
)

func file_api_recommendation_v1_recommendation_proto_rawDescGZIP() []byte {
	file_api_recommendation_v1_recommendation_proto_rawDescOnce.Do(func() {
		file_api_recommendation_v1_recommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_recommendation_v1_recommendation_proto_rawDesc), len(file_api_recommendation_v1_recommendation_proto_rawDesc)))
	})
	return file_api_recommendation_v1_recommendation_proto_rawDescData
}

var file_api_recommendation_v1_recommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_recommendation_v1_recommendation_proto_goTypes = []any{
	(*GetRecommendedProductsRequest)(nil),  // 0: recommendation.v1.GetRecommendedProductsRequest
	(*GetRecommendedProductsResponse)(nil), // 1: recommendation.v1.GetRecommendedProductsResponse
	(*Product)(nil),                        // 2: recommendation.v1.Product
}
var file_api_recommendation_v1_recommendation_proto_depIdxs = []int32{
	2, // 0: recommendation.v1.GetRecommendedProductsResponse.products:type_name -> recommendation.v1.Product
	0, // 1: recommendation.v1.RecommendationService.GetRecommendedProducts:input_type -> recommendation.v1.GetRecommendedProductsRequest
	1, // 2: recommendation.v1.RecommendationService.GetRecommendedProducts:output_type -> recommendation.v1.GetRecommendedProductsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_recommendation_v1_recommendation_proto_init() }
func file_api_recommendation_v1_recommendation_proto_init() {
	if File_api_recommendation_v1_recommendation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_recommendation_v1_recommendation_proto_rawDesc), len(file_api_recommendation_v1_recommendation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_recommendation_v1_recommendation_proto_goTypes,
		DependencyIndexes: file_api_recommendation_v1_recommendation_proto_depIdxs,
		MessageInfos:      file_api_recommendation_v1_recommendation_proto_msgTypes,
	}.Build()
	File_api_recommendation_v1_recommendation_proto = out.File
	file_api_recommendation_v1_recommendation_proto_goTypes = nil
	file_api_recommendation_v1_recommendation_proto_depIdxs = nil
}
