[server]
  name = "crossborder"
  port = 9095

[database]
  driver = "mysql"
  source = "root:password@tcp(127.0.0.1:3306)/ecommerce_crossborder?charset=utf8mb4&parseTime=True&loc=Local"

[log]
  level = "info"
