// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/cart/v1/cart.proto

package v1

import (
	v1 "ecommerce/api/product/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CartItem 购物车中的商品项
type CartItem struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SkuId    uint64                 `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"` // 商品SKU ID
	Quantity uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`        // 数量
	// 商品的详细信息, 从商品服务获取后填充
	SkuInfo       *v1.SkuInfo `protobuf:"bytes,3,opt,name=sku_info,json=skuInfo,proto3" json:"sku_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{0}
}

func (x *CartItem) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CartItem) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItem) GetSkuInfo() *v1.SkuInfo {
	if x != nil {
		return x.SkuInfo
	}
	return nil
}

// AddItemRequest 添加商品请求
// 注意：user_id 将从网关解析JWT后通过gRPC metadata传递，不在请求体中
type AddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         uint64                 `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"` // 要添加的商品SKU ID
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`        // 数量
	Checked       *bool                  `protobuf:"varint,3,opt,name=checked,proto3,oneof" json:"checked,omitempty"`    // 是否勾选，默认为true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRequest.ProtoReflect.Descriptor instead.
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{1}
}

func (x *AddItemRequest) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *AddItemRequest) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AddItemRequest) GetChecked() bool {
	if x != nil && x.Checked != nil {
		return *x.Checked
	}
	return false
}

// AddItemResponse 添加商品响应
type AddItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemResponse) Reset() {
	*x = AddItemResponse{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemResponse) ProtoMessage() {}

func (x *AddItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemResponse.ProtoReflect.Descriptor instead.
func (*AddItemResponse) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{2}
}

// RemoveItemRequest 移除商品请求
type RemoveItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         uint64                 `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"` // 要移除的商品SKU ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemRequest) Reset() {
	*x = RemoveItemRequest{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemRequest) ProtoMessage() {}

func (x *RemoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveItemRequest) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveItemRequest) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

// RemoveItemResponse 移除商品响应
type RemoveItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemResponse) Reset() {
	*x = RemoveItemResponse{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemResponse) ProtoMessage() {}

func (x *RemoveItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemResponse.ProtoReflect.Descriptor instead.
func (*RemoveItemResponse) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{4}
}

// UpdateItemRequest 更新商品数量请求
type UpdateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         uint64                 `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"` // 要更新的商品SKU ID
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`        // 更新后的最终数量, 如果为0则删除该商品
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateItemRequest) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *UpdateItemRequest) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// UpdateItemResponse 更新商品数量响应
type UpdateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemResponse) Reset() {
	*x = UpdateItemResponse{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemResponse) ProtoMessage() {}

func (x *UpdateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateItemResponse) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{6}
}

// GetCartRequest 获取购物车请求
type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{7}
}

// GetCartResponse 获取购物车响应
type GetCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CartItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 购物车中的所有商品项
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartResponse) Reset() {
	*x = GetCartResponse{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartResponse) ProtoMessage() {}

func (x *GetCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartResponse.ProtoReflect.Descriptor instead.
func (*GetCartResponse) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{8}
}

func (x *GetCartResponse) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ClearCheckedItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCheckedItemsRequest) Reset() {
	*x = ClearCheckedItemsRequest{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCheckedItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCheckedItemsRequest) ProtoMessage() {}

func (x *ClearCheckedItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCheckedItemsRequest.ProtoReflect.Descriptor instead.
func (*ClearCheckedItemsRequest) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{9}
}

func (x *ClearCheckedItemsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ClearCheckedItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCheckedItemsResponse) Reset() {
	*x = ClearCheckedItemsResponse{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCheckedItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCheckedItemsResponse) ProtoMessage() {}

func (x *ClearCheckedItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCheckedItemsResponse.ProtoReflect.Descriptor instead.
func (*ClearCheckedItemsResponse) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{10}
}

var File_api_cart_v1_cart_proto protoreflect.FileDescriptor

const file_api_cart_v1_cart_proto_rawDesc = "" +
	"\n" +
	"\x16api/cart/v1/cart.proto\x12\vapi.cart.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1capi/product/v1/product.proto\"q\n" +
	"\bCartItem\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\x04R\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\x122\n" +
	"\bsku_info\x18\x03 \x01(\v2\x17.api.product.v1.SkuInfoR\askuInfo\"n\n" +
	"\x0eAddItemRequest\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\x04R\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\x12\x1d\n" +
	"\achecked\x18\x03 \x01(\bH\x00R\achecked\x88\x01\x01B\n" +
	"\n" +
	"\b_checked\"\x11\n" +
	"\x0fAddItemResponse\"*\n" +
	"\x11RemoveItemRequest\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\x04R\x05skuId\"\x14\n" +
	"\x12RemoveItemResponse\"F\n" +
	"\x11UpdateItemRequest\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\x04R\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\"\x14\n" +
	"\x12UpdateItemResponse\"\x10\n" +
	"\x0eGetCartRequest\">\n" +
	"\x0fGetCartResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.api.cart.v1.CartItemR\x05items\"3\n" +
	"\x18ClearCheckedItemsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\x1b\n" +
	"\x19ClearCheckedItemsResponse2\x8f\x04\n" +
	"\vCartService\x12_\n" +
	"\aAddItem\x12\x1b.api.cart.v1.AddItemRequest\x1a\x1c.api.cart.v1.AddItemResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/cart/items\x12n\n" +
	"\n" +
	"RemoveItem\x12\x1e.api.cart.v1.RemoveItemRequest\x1a\x1f.api.cart.v1.RemoveItemResponse\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/v1/cart/items/{sku_id}\x12q\n" +
	"\n" +
	"UpdateItem\x12\x1e.api.cart.v1.UpdateItemRequest\x1a\x1f.api.cart.v1.UpdateItemResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/v1/cart/items/{sku_id}\x12V\n" +
	"\aGetCart\x12\x1b.api.cart.v1.GetCartRequest\x1a\x1c.api.cart.v1.GetCartResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/cart\x12d\n" +
	"\x11ClearCheckedItems\x12%.api.cart.v1.ClearCheckedItemsRequest\x1a&.api.cart.v1.ClearCheckedItemsResponse\"\x00B\x1aZ\x18ecommerce/api/cart/v1;v1b\x06proto3"

var (
	file_api_cart_v1_cart_proto_rawDescOnce sync.Once
	file_api_cart_v1_cart_proto_rawDescData []byte
)

func file_api_cart_v1_cart_proto_rawDescGZIP() []byte {
	file_api_cart_v1_cart_proto_rawDescOnce.Do(func() {
		file_api_cart_v1_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_cart_v1_cart_proto_rawDesc), len(file_api_cart_v1_cart_proto_rawDesc)))
	})
	return file_api_cart_v1_cart_proto_rawDescData
}

var file_api_cart_v1_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_cart_v1_cart_proto_goTypes = []any{
	(*CartItem)(nil),                  // 0: api.cart.v1.CartItem
	(*AddItemRequest)(nil),            // 1: api.cart.v1.AddItemRequest
	(*AddItemResponse)(nil),           // 2: api.cart.v1.AddItemResponse
	(*RemoveItemRequest)(nil),         // 3: api.cart.v1.RemoveItemRequest
	(*RemoveItemResponse)(nil),        // 4: api.cart.v1.RemoveItemResponse
	(*UpdateItemRequest)(nil),         // 5: api.cart.v1.UpdateItemRequest
	(*UpdateItemResponse)(nil),        // 6: api.cart.v1.UpdateItemResponse
	(*GetCartRequest)(nil),            // 7: api.cart.v1.GetCartRequest
	(*GetCartResponse)(nil),           // 8: api.cart.v1.GetCartResponse
	(*ClearCheckedItemsRequest)(nil),  // 9: api.cart.v1.ClearCheckedItemsRequest
	(*ClearCheckedItemsResponse)(nil), // 10: api.cart.v1.ClearCheckedItemsResponse
	(*v1.SkuInfo)(nil),                // 11: api.product.v1.SkuInfo
}
var file_api_cart_v1_cart_proto_depIdxs = []int32{
	11, // 0: api.cart.v1.CartItem.sku_info:type_name -> api.product.v1.SkuInfo
	0,  // 1: api.cart.v1.GetCartResponse.items:type_name -> api.cart.v1.CartItem
	1,  // 2: api.cart.v1.CartService.AddItem:input_type -> api.cart.v1.AddItemRequest
	3,  // 3: api.cart.v1.CartService.RemoveItem:input_type -> api.cart.v1.RemoveItemRequest
	5,  // 4: api.cart.v1.CartService.UpdateItem:input_type -> api.cart.v1.UpdateItemRequest
	7,  // 5: api.cart.v1.CartService.GetCart:input_type -> api.cart.v1.GetCartRequest
	9,  // 6: api.cart.v1.CartService.ClearCheckedItems:input_type -> api.cart.v1.ClearCheckedItemsRequest
	2,  // 7: api.cart.v1.CartService.AddItem:output_type -> api.cart.v1.AddItemResponse
	4,  // 8: api.cart.v1.CartService.RemoveItem:output_type -> api.cart.v1.RemoveItemResponse
	6,  // 9: api.cart.v1.CartService.UpdateItem:output_type -> api.cart.v1.UpdateItemResponse
	8,  // 10: api.cart.v1.CartService.GetCart:output_type -> api.cart.v1.GetCartResponse
	10, // 11: api.cart.v1.CartService.ClearCheckedItems:output_type -> api.cart.v1.ClearCheckedItemsResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_cart_v1_cart_proto_init() }
func file_api_cart_v1_cart_proto_init() {
	if File_api_cart_v1_cart_proto != nil {
		return
	}
	file_api_cart_v1_cart_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_cart_v1_cart_proto_rawDesc), len(file_api_cart_v1_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_cart_v1_cart_proto_goTypes,
		DependencyIndexes: file_api_cart_v1_cart_proto_depIdxs,
		MessageInfos:      file_api_cart_v1_cart_proto_msgTypes,
	}.Build()
	File_api_cart_v1_cart_proto = out.File
	file_api_cart_v1_cart_proto_goTypes = nil
	file_api_cart_v1_cart_proto_depIdxs = nil
}
