// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: ecommerce/api/marketing/v1/marketing.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Admin ---
type CreateCouponTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCouponTemplateRequest) Reset() {
	*x = CreateCouponTemplateRequest{}
	mi := &file_ecommerce_api_marketing_v1_marketing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCouponTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCouponTemplateRequest) ProtoMessage() {}

func (x *CreateCouponTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_marketing_v1_marketing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCouponTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateCouponTemplateRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_marketing_v1_marketing_proto_rawDescGZIP(), []int{0}
}

type CreateCouponTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    uint64                 `protobuf:"varint,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCouponTemplateResponse) Reset() {
	*x = CreateCouponTemplateResponse{}
	mi := &file_ecommerce_api_marketing_v1_marketing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCouponTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCouponTemplateResponse) ProtoMessage() {}

func (x *CreateCouponTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_marketing_v1_marketing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCouponTemplateResponse.ProtoReflect.Descriptor instead.
func (*CreateCouponTemplateResponse) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_marketing_v1_marketing_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCouponTemplateResponse) GetTemplateId() uint64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

// --- User ---
type ClaimCouponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TemplateId    uint64                 `protobuf:"varint,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimCouponRequest) Reset() {
	*x = ClaimCouponRequest{}
	mi := &file_ecommerce_api_marketing_v1_marketing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimCouponRequest) ProtoMessage() {}

func (x *ClaimCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_marketing_v1_marketing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimCouponRequest.ProtoReflect.Descriptor instead.
func (*ClaimCouponRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_marketing_v1_marketing_proto_rawDescGZIP(), []int{2}
}

func (x *ClaimCouponRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ClaimCouponRequest) GetTemplateId() uint64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

type ClaimCouponResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimCouponResponse) Reset() {
	*x = ClaimCouponResponse{}
	mi := &file_ecommerce_api_marketing_v1_marketing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimCouponResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimCouponResponse) ProtoMessage() {}

func (x *ClaimCouponResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_marketing_v1_marketing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimCouponResponse.ProtoReflect.Descriptor instead.
func (*ClaimCouponResponse) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_marketing_v1_marketing_proto_rawDescGZIP(), []int{3}
}

type UserCouponInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserCouponId  uint64                 `protobuf:"varint,1,opt,name=user_coupon_id,json=userCouponId,proto3" json:"user_coupon_id,omitempty"`
	TemplateId    uint64                 `protobuf:"varint,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	ValidFrom     string                 `protobuf:"bytes,5,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo       string                 `protobuf:"bytes,6,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"` // ... 其他需要在前端展示的规则信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCouponInfo) Reset() {
	*x = UserCouponInfo{}
	mi := &file_ecommerce_api_marketing_v1_marketing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCouponInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCouponInfo) ProtoMessage() {}

func (x *UserCouponInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_marketing_v1_marketing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCouponInfo.ProtoReflect.Descriptor instead.
func (*UserCouponInfo) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_marketing_v1_marketing_proto_rawDescGZIP(), []int{4}
}

func (x *UserCouponInfo) GetUserCouponId() uint64 {
	if x != nil {
		return x.UserCouponId
	}
	return 0
}

func (x *UserCouponInfo) GetTemplateId() uint64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *UserCouponInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UserCouponInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserCouponInfo) GetValidFrom() string {
	if x != nil {
		return x.ValidFrom
	}
	return ""
}

func (x *UserCouponInfo) GetValidTo() string {
	if x != nil {
		return x.ValidTo
	}
	return ""
}

type ListMyCouponsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 1-未使用, 2-已使用, 3-已过期
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyCouponsRequest) Reset() {
	*x = ListMyCouponsRequest{}
	mi := &file_ecommerce_api_marketing_v1_marketing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyCouponsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyCouponsRequest) ProtoMessage() {}

func (x *ListMyCouponsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_marketing_v1_marketing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyCouponsRequest.ProtoReflect.Descriptor instead.
func (*ListMyCouponsRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_marketing_v1_marketing_proto_rawDescGZIP(), []int{5}
}

func (x *ListMyCouponsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListMyCouponsRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListMyCouponsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coupons       []*UserCouponInfo      `protobuf:"bytes,1,rep,name=coupons,proto3" json:"coupons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyCouponsResponse) Reset() {
	*x = ListMyCouponsResponse{}
	mi := &file_ecommerce_api_marketing_v1_marketing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyCouponsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyCouponsResponse) ProtoMessage() {}

func (x *ListMyCouponsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_marketing_v1_marketing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyCouponsResponse.ProtoReflect.Descriptor instead.
func (*ListMyCouponsResponse) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_marketing_v1_marketing_proto_rawDescGZIP(), []int{6}
}

func (x *ListMyCouponsResponse) GetCoupons() []*UserCouponInfo {
	if x != nil {
		return x.Coupons
	}
	return nil
}

// --- Internal ---
type OrderItemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         uint64                 `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	SpuId         uint64                 `protobuf:"varint,2,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	CategoryId    uint64                 `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Price         uint64                 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      uint32                 `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemInfo) Reset() {
	*x = OrderItemInfo{}
	mi := &file_ecommerce_api_marketing_v1_marketing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemInfo) ProtoMessage() {}

func (x *OrderItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_marketing_v1_marketing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemInfo.ProtoReflect.Descriptor instead.
func (*OrderItemInfo) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_marketing_v1_marketing_proto_rawDescGZIP(), []int{7}
}

func (x *OrderItemInfo) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *OrderItemInfo) GetSpuId() uint64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *OrderItemInfo) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *OrderItemInfo) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItemInfo) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CalculateDiscountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CouponCode    string                 `protobuf:"bytes,2,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
	Items         []*OrderItemInfo       `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateDiscountRequest) Reset() {
	*x = CalculateDiscountRequest{}
	mi := &file_ecommerce_api_marketing_v1_marketing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateDiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateDiscountRequest) ProtoMessage() {}

func (x *CalculateDiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_marketing_v1_marketing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateDiscountRequest.ProtoReflect.Descriptor instead.
func (*CalculateDiscountRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_marketing_v1_marketing_proto_rawDescGZIP(), []int{8}
}

func (x *CalculateDiscountRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CalculateDiscountRequest) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

func (x *CalculateDiscountRequest) GetItems() []*OrderItemInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type CalculateDiscountResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DiscountAmount uint64                 `protobuf:"varint,1,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"` // 优惠的金额(分)
	FinalAmount    uint64                 `protobuf:"varint,2,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`          // 优惠后的金额(分)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CalculateDiscountResponse) Reset() {
	*x = CalculateDiscountResponse{}
	mi := &file_ecommerce_api_marketing_v1_marketing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateDiscountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateDiscountResponse) ProtoMessage() {}

func (x *CalculateDiscountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_marketing_v1_marketing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateDiscountResponse.ProtoReflect.Descriptor instead.
func (*CalculateDiscountResponse) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_marketing_v1_marketing_proto_rawDescGZIP(), []int{9}
}

func (x *CalculateDiscountResponse) GetDiscountAmount() uint64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *CalculateDiscountResponse) GetFinalAmount() uint64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

var File_ecommerce_api_marketing_v1_marketing_proto protoreflect.FileDescriptor

const file_ecommerce_api_marketing_v1_marketing_proto_rawDesc = "" +
	"\n" +
	"*ecommerce/api/marketing/v1/marketing.proto\x12\x10api.marketing.v1\x1a\x1cgoogle/api/annotations.proto\"\x1d\n" +
	"\x1bCreateCouponTemplateRequest\"?\n" +
	"\x1cCreateCouponTemplateResponse\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\x04R\n" +
	"templateId\"N\n" +
	"\x12ClaimCouponRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\x04R\n" +
	"templateId\"\x15\n" +
	"\x13ClaimCouponResponse\"\xbf\x01\n" +
	"\x0eUserCouponInfo\x12$\n" +
	"\x0euser_coupon_id\x18\x01 \x01(\x04R\fuserCouponId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\x04R\n" +
	"templateId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"valid_from\x18\x05 \x01(\tR\tvalidFrom\x12\x19\n" +
	"\bvalid_to\x18\x06 \x01(\tR\avalidTo\"G\n" +
	"\x14ListMyCouponsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"S\n" +
	"\x15ListMyCouponsResponse\x12:\n" +
	"\acoupons\x18\x01 \x03(\v2 .api.marketing.v1.UserCouponInfoR\acoupons\"\x90\x01\n" +
	"\rOrderItemInfo\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\x04R\x05skuId\x12\x15\n" +
	"\x06spu_id\x18\x02 \x01(\x04R\x05spuId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x04R\n" +
	"categoryId\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x04R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\rR\bquantity\"\x8b\x01\n" +
	"\x18CalculateDiscountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1f\n" +
	"\vcoupon_code\x18\x02 \x01(\tR\n" +
	"couponCode\x125\n" +
	"\x05items\x18\x03 \x03(\v2\x1f.api.marketing.v1.OrderItemInfoR\x05items\"g\n" +
	"\x19CalculateDiscountResponse\x12'\n" +
	"\x0fdiscount_amount\x18\x01 \x01(\x04R\x0ediscountAmount\x12!\n" +
	"\ffinal_amount\x18\x02 \x01(\x04R\vfinalAmount2\xe8\x03\n" +
	"\tMarketing\x12w\n" +
	"\x14CreateCouponTemplate\x12-.api.marketing.v1.CreateCouponTemplateRequest\x1a..api.marketing.v1.CreateCouponTemplateResponse\"\x00\x12x\n" +
	"\vClaimCoupon\x12$.api.marketing.v1.ClaimCouponRequest\x1a%.api.marketing.v1.ClaimCouponResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/coupons/claim\x12x\n" +
	"\rListMyCoupons\x12&.api.marketing.v1.ListMyCouponsRequest\x1a'.api.marketing.v1.ListMyCouponsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/my/coupons\x12n\n" +
	"\x11CalculateDiscount\x12*.api.marketing.v1.CalculateDiscountRequest\x1a+.api.marketing.v1.CalculateDiscountResponse\"\x00B)Z'ecommerce/ecommerce/api/marketing/v1;v1b\x06proto3"

var (
	file_ecommerce_api_marketing_v1_marketing_proto_rawDescOnce sync.Once
	file_ecommerce_api_marketing_v1_marketing_proto_rawDescData []byte
)

func file_ecommerce_api_marketing_v1_marketing_proto_rawDescGZIP() []byte {
	file_ecommerce_api_marketing_v1_marketing_proto_rawDescOnce.Do(func() {
		file_ecommerce_api_marketing_v1_marketing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ecommerce_api_marketing_v1_marketing_proto_rawDesc), len(file_ecommerce_api_marketing_v1_marketing_proto_rawDesc)))
	})
	return file_ecommerce_api_marketing_v1_marketing_proto_rawDescData
}

var file_ecommerce_api_marketing_v1_marketing_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ecommerce_api_marketing_v1_marketing_proto_goTypes = []any{
	(*CreateCouponTemplateRequest)(nil),  // 0: api.marketing.v1.CreateCouponTemplateRequest
	(*CreateCouponTemplateResponse)(nil), // 1: api.marketing.v1.CreateCouponTemplateResponse
	(*ClaimCouponRequest)(nil),           // 2: api.marketing.v1.ClaimCouponRequest
	(*ClaimCouponResponse)(nil),          // 3: api.marketing.v1.ClaimCouponResponse
	(*UserCouponInfo)(nil),               // 4: api.marketing.v1.UserCouponInfo
	(*ListMyCouponsRequest)(nil),         // 5: api.marketing.v1.ListMyCouponsRequest
	(*ListMyCouponsResponse)(nil),        // 6: api.marketing.v1.ListMyCouponsResponse
	(*OrderItemInfo)(nil),                // 7: api.marketing.v1.OrderItemInfo
	(*CalculateDiscountRequest)(nil),     // 8: api.marketing.v1.CalculateDiscountRequest
	(*CalculateDiscountResponse)(nil),    // 9: api.marketing.v1.CalculateDiscountResponse
}
var file_ecommerce_api_marketing_v1_marketing_proto_depIdxs = []int32{
	4, // 0: api.marketing.v1.ListMyCouponsResponse.coupons:type_name -> api.marketing.v1.UserCouponInfo
	7, // 1: api.marketing.v1.CalculateDiscountRequest.items:type_name -> api.marketing.v1.OrderItemInfo
	0, // 2: api.marketing.v1.Marketing.CreateCouponTemplate:input_type -> api.marketing.v1.CreateCouponTemplateRequest
	2, // 3: api.marketing.v1.Marketing.ClaimCoupon:input_type -> api.marketing.v1.ClaimCouponRequest
	5, // 4: api.marketing.v1.Marketing.ListMyCoupons:input_type -> api.marketing.v1.ListMyCouponsRequest
	8, // 5: api.marketing.v1.Marketing.CalculateDiscount:input_type -> api.marketing.v1.CalculateDiscountRequest
	1, // 6: api.marketing.v1.Marketing.CreateCouponTemplate:output_type -> api.marketing.v1.CreateCouponTemplateResponse
	3, // 7: api.marketing.v1.Marketing.ClaimCoupon:output_type -> api.marketing.v1.ClaimCouponResponse
	6, // 8: api.marketing.v1.Marketing.ListMyCoupons:output_type -> api.marketing.v1.ListMyCouponsResponse
	9, // 9: api.marketing.v1.Marketing.CalculateDiscount:output_type -> api.marketing.v1.CalculateDiscountResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ecommerce_api_marketing_v1_marketing_proto_init() }
func file_ecommerce_api_marketing_v1_marketing_proto_init() {
	if File_ecommerce_api_marketing_v1_marketing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ecommerce_api_marketing_v1_marketing_proto_rawDesc), len(file_ecommerce_api_marketing_v1_marketing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ecommerce_api_marketing_v1_marketing_proto_goTypes,
		DependencyIndexes: file_ecommerce_api_marketing_v1_marketing_proto_depIdxs,
		MessageInfos:      file_ecommerce_api_marketing_v1_marketing_proto_msgTypes,
	}.Build()
	File_ecommerce_api_marketing_v1_marketing_proto = out.File
	file_ecommerce_api_marketing_v1_marketing_proto_goTypes = nil
	file_ecommerce_api_marketing_v1_marketing_proto_depIdxs = nil
}
