// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: ecommerce/api/marketing/v1/marketing.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Marketing_CreateCouponTemplate_FullMethodName = "/api.marketing.v1.Marketing/CreateCouponTemplate"
	Marketing_ClaimCoupon_FullMethodName          = "/api.marketing.v1.Marketing/ClaimCoupon"
	Marketing_ListMyCoupons_FullMethodName        = "/api.marketing.v1.Marketing/ListMyCoupons"
	Marketing_CalculateDiscount_FullMethodName    = "/api.marketing.v1.Marketing/CalculateDiscount"
)

// MarketingClient is the client API for Marketing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ===================================
// Service Definition
// ===================================
type MarketingClient interface {
	// --- Admin Facing ---
	// 创建优惠券模板
	CreateCouponTemplate(ctx context.Context, in *CreateCouponTemplateRequest, opts ...grpc.CallOption) (*CreateCouponTemplateResponse, error)
	// --- User Facing ---
	// 用户领取优惠券
	ClaimCoupon(ctx context.Context, in *ClaimCouponRequest, opts ...grpc.CallOption) (*ClaimCouponResponse, error)
	// 查看我的优惠券
	ListMyCoupons(ctx context.Context, in *ListMyCouponsRequest, opts ...grpc.CallOption) (*ListMyCouponsResponse, error)
	// --- Internal Service Facing ---
	// 为订单服务计算优惠金额
	CalculateDiscount(ctx context.Context, in *CalculateDiscountRequest, opts ...grpc.CallOption) (*CalculateDiscountResponse, error)
}

type marketingClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketingClient(cc grpc.ClientConnInterface) MarketingClient {
	return &marketingClient{cc}
}

func (c *marketingClient) CreateCouponTemplate(ctx context.Context, in *CreateCouponTemplateRequest, opts ...grpc.CallOption) (*CreateCouponTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCouponTemplateResponse)
	err := c.cc.Invoke(ctx, Marketing_CreateCouponTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) ClaimCoupon(ctx context.Context, in *ClaimCouponRequest, opts ...grpc.CallOption) (*ClaimCouponResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimCouponResponse)
	err := c.cc.Invoke(ctx, Marketing_ClaimCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) ListMyCoupons(ctx context.Context, in *ListMyCouponsRequest, opts ...grpc.CallOption) (*ListMyCouponsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyCouponsResponse)
	err := c.cc.Invoke(ctx, Marketing_ListMyCoupons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) CalculateDiscount(ctx context.Context, in *CalculateDiscountRequest, opts ...grpc.CallOption) (*CalculateDiscountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateDiscountResponse)
	err := c.cc.Invoke(ctx, Marketing_CalculateDiscount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketingServer is the server API for Marketing service.
// All implementations must embed UnimplementedMarketingServer
// for forward compatibility.
//
// ===================================
// Service Definition
// ===================================
type MarketingServer interface {
	// --- Admin Facing ---
	// 创建优惠券模板
	CreateCouponTemplate(context.Context, *CreateCouponTemplateRequest) (*CreateCouponTemplateResponse, error)
	// --- User Facing ---
	// 用户领取优惠券
	ClaimCoupon(context.Context, *ClaimCouponRequest) (*ClaimCouponResponse, error)
	// 查看我的优惠券
	ListMyCoupons(context.Context, *ListMyCouponsRequest) (*ListMyCouponsResponse, error)
	// --- Internal Service Facing ---
	// 为订单服务计算优惠金额
	CalculateDiscount(context.Context, *CalculateDiscountRequest) (*CalculateDiscountResponse, error)
	mustEmbedUnimplementedMarketingServer()
}

// UnimplementedMarketingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketingServer struct{}

func (UnimplementedMarketingServer) CreateCouponTemplate(context.Context, *CreateCouponTemplateRequest) (*CreateCouponTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCouponTemplate not implemented")
}
func (UnimplementedMarketingServer) ClaimCoupon(context.Context, *ClaimCouponRequest) (*ClaimCouponResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimCoupon not implemented")
}
func (UnimplementedMarketingServer) ListMyCoupons(context.Context, *ListMyCouponsRequest) (*ListMyCouponsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMyCoupons not implemented")
}
func (UnimplementedMarketingServer) CalculateDiscount(context.Context, *CalculateDiscountRequest) (*CalculateDiscountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateDiscount not implemented")
}
func (UnimplementedMarketingServer) mustEmbedUnimplementedMarketingServer() {}
func (UnimplementedMarketingServer) testEmbeddedByValue()                   {}

// UnsafeMarketingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketingServer will
// result in compilation errors.
type UnsafeMarketingServer interface {
	mustEmbedUnimplementedMarketingServer()
}

func RegisterMarketingServer(s grpc.ServiceRegistrar, srv MarketingServer) {
	// If the following call pancis, it indicates UnimplementedMarketingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Marketing_ServiceDesc, srv)
}

func _Marketing_CreateCouponTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCouponTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).CreateCouponTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_CreateCouponTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).CreateCouponTemplate(ctx, req.(*CreateCouponTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_ClaimCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).ClaimCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_ClaimCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).ClaimCoupon(ctx, req.(*ClaimCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_ListMyCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyCouponsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).ListMyCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_ListMyCoupons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).ListMyCoupons(ctx, req.(*ListMyCouponsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_CalculateDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateDiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).CalculateDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_CalculateDiscount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).CalculateDiscount(ctx, req.(*CalculateDiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Marketing_ServiceDesc is the grpc.ServiceDesc for Marketing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Marketing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.marketing.v1.Marketing",
	HandlerType: (*MarketingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCouponTemplate",
			Handler:    _Marketing_CreateCouponTemplate_Handler,
		},
		{
			MethodName: "ClaimCoupon",
			Handler:    _Marketing_ClaimCoupon_Handler,
		},
		{
			MethodName: "ListMyCoupons",
			Handler:    _Marketing_ListMyCoupons_Handler,
		},
		{
			MethodName: "CalculateDiscount",
			Handler:    _Marketing_CalculateDiscount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ecommerce/api/marketing/v1/marketing.proto",
}
