// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.32.1
// source: api/marketing/v1/marketing.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MarketingClient is the client API for Marketing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketingClient interface {
	// --- Admin Facing ---
	// 创建优惠券模板
	CreateCouponTemplate(ctx context.Context, in *CreateCouponTemplateRequest, opts ...grpc.CallOption) (*CreateCouponTemplateResponse, error)
	// --- User Facing ---
	// 用户领取优惠券
	ClaimCoupon(ctx context.Context, in *ClaimCouponRequest, opts ...grpc.CallOption) (*ClaimCouponResponse, error)
	// 查看我的优惠券
	ListMyCoupons(ctx context.Context, in *ListMyCouponsRequest, opts ...grpc.CallOption) (*ListMyCouponsResponse, error)
	// --- Internal Service Facing ---
	// 为订单服务计算优惠金额
	CalculateDiscount(ctx context.Context, in *CalculateDiscountRequest, opts ...grpc.CallOption) (*CalculateDiscountResponse, error)
	// --- 促销管理 ---
	CreatePromotion(ctx context.Context, in *CreatePromotionRequest, opts ...grpc.CallOption) (*PromotionInfo, error)
	UpdatePromotion(ctx context.Context, in *UpdatePromotionRequest, opts ...grpc.CallOption) (*PromotionInfo, error)
	DeletePromotion(ctx context.Context, in *DeletePromotionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetPromotion(ctx context.Context, in *GetPromotionRequest, opts ...grpc.CallOption) (*PromotionInfo, error)
	ListPromotions(ctx context.Context, in *ListPromotionsRequest, opts ...grpc.CallOption) (*ListPromotionsResponse, error)
}

type marketingClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketingClient(cc grpc.ClientConnInterface) MarketingClient {
	return &marketingClient{cc}
}

func (c *marketingClient) CreateCouponTemplate(ctx context.Context, in *CreateCouponTemplateRequest, opts ...grpc.CallOption) (*CreateCouponTemplateResponse, error) {
	out := new(CreateCouponTemplateResponse)
	err := c.cc.Invoke(ctx, "/api.marketing.v1.Marketing/CreateCouponTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) ClaimCoupon(ctx context.Context, in *ClaimCouponRequest, opts ...grpc.CallOption) (*ClaimCouponResponse, error) {
	out := new(ClaimCouponResponse)
	err := c.cc.Invoke(ctx, "/api.marketing.v1.Marketing/ClaimCoupon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) ListMyCoupons(ctx context.Context, in *ListMyCouponsRequest, opts ...grpc.CallOption) (*ListMyCouponsResponse, error) {
	out := new(ListMyCouponsResponse)
	err := c.cc.Invoke(ctx, "/api.marketing.v1.Marketing/ListMyCoupons", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) CalculateDiscount(ctx context.Context, in *CalculateDiscountRequest, opts ...grpc.CallOption) (*CalculateDiscountResponse, error) {
	out := new(CalculateDiscountResponse)
	err := c.cc.Invoke(ctx, "/api.marketing.v1.Marketing/CalculateDiscount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) CreatePromotion(ctx context.Context, in *CreatePromotionRequest, opts ...grpc.CallOption) (*PromotionInfo, error) {
	out := new(PromotionInfo)
	err := c.cc.Invoke(ctx, "/api.marketing.v1.Marketing/CreatePromotion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) UpdatePromotion(ctx context.Context, in *UpdatePromotionRequest, opts ...grpc.CallOption) (*PromotionInfo, error) {
	out := new(PromotionInfo)
	err := c.cc.Invoke(ctx, "/api.marketing.v1.Marketing/UpdatePromotion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) DeletePromotion(ctx context.Context, in *DeletePromotionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/api.marketing.v1.Marketing/DeletePromotion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) GetPromotion(ctx context.Context, in *GetPromotionRequest, opts ...grpc.CallOption) (*PromotionInfo, error) {
	out := new(PromotionInfo)
	err := c.cc.Invoke(ctx, "/api.marketing.v1.Marketing/GetPromotion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) ListPromotions(ctx context.Context, in *ListPromotionsRequest, opts ...grpc.CallOption) (*ListPromotionsResponse, error) {
	out := new(ListPromotionsResponse)
	err := c.cc.Invoke(ctx, "/api.marketing.v1.Marketing/ListPromotions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketingServer is the server API for Marketing service.
// All implementations must embed UnimplementedMarketingServer
// for forward compatibility
type MarketingServer interface {
	// --- Admin Facing ---
	// 创建优惠券模板
	CreateCouponTemplate(context.Context, *CreateCouponTemplateRequest) (*CreateCouponTemplateResponse, error)
	// --- User Facing ---
	// 用户领取优惠券
	ClaimCoupon(context.Context, *ClaimCouponRequest) (*ClaimCouponResponse, error)
	// 查看我的优惠券
	ListMyCoupons(context.Context, *ListMyCouponsRequest) (*ListMyCouponsResponse, error)
	// --- Internal Service Facing ---
	// 为订单服务计算优惠金额
	CalculateDiscount(context.Context, *CalculateDiscountRequest) (*CalculateDiscountResponse, error)
	// --- 促销管理 ---
	CreatePromotion(context.Context, *CreatePromotionRequest) (*PromotionInfo, error)
	UpdatePromotion(context.Context, *UpdatePromotionRequest) (*PromotionInfo, error)
	DeletePromotion(context.Context, *DeletePromotionRequest) (*emptypb.Empty, error)
	GetPromotion(context.Context, *GetPromotionRequest) (*PromotionInfo, error)
	ListPromotions(context.Context, *ListPromotionsRequest) (*ListPromotionsResponse, error)
	mustEmbedUnimplementedMarketingServer()
}

// UnimplementedMarketingServer must be embedded to have forward compatible implementations.
type UnimplementedMarketingServer struct {
}

func (UnimplementedMarketingServer) CreateCouponTemplate(context.Context, *CreateCouponTemplateRequest) (*CreateCouponTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCouponTemplate not implemented")
}
func (UnimplementedMarketingServer) ClaimCoupon(context.Context, *ClaimCouponRequest) (*ClaimCouponResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimCoupon not implemented")
}
func (UnimplementedMarketingServer) ListMyCoupons(context.Context, *ListMyCouponsRequest) (*ListMyCouponsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMyCoupons not implemented")
}
func (UnimplementedMarketingServer) CalculateDiscount(context.Context, *CalculateDiscountRequest) (*CalculateDiscountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateDiscount not implemented")
}
func (UnimplementedMarketingServer) CreatePromotion(context.Context, *CreatePromotionRequest) (*PromotionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePromotion not implemented")
}
func (UnimplementedMarketingServer) UpdatePromotion(context.Context, *UpdatePromotionRequest) (*PromotionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePromotion not implemented")
}
func (UnimplementedMarketingServer) DeletePromotion(context.Context, *DeletePromotionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePromotion not implemented")
}
func (UnimplementedMarketingServer) GetPromotion(context.Context, *GetPromotionRequest) (*PromotionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPromotion not implemented")
}
func (UnimplementedMarketingServer) ListPromotions(context.Context, *ListPromotionsRequest) (*ListPromotionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPromotions not implemented")
}
func (UnimplementedMarketingServer) mustEmbedUnimplementedMarketingServer() {}

// UnsafeMarketingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketingServer will
// result in compilation errors.
type UnsafeMarketingServer interface {
	mustEmbedUnimplementedMarketingServer()
}

func RegisterMarketingServer(s grpc.ServiceRegistrar, srv MarketingServer) {
	s.RegisterService(&Marketing_ServiceDesc, srv)
}

func _Marketing_CreateCouponTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCouponTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).CreateCouponTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.marketing.v1.Marketing/CreateCouponTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).CreateCouponTemplate(ctx, req.(*CreateCouponTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_ClaimCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).ClaimCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.marketing.v1.Marketing/ClaimCoupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).ClaimCoupon(ctx, req.(*ClaimCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_ListMyCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyCouponsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).ListMyCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.marketing.v1.Marketing/ListMyCoupons",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).ListMyCoupons(ctx, req.(*ListMyCouponsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_CalculateDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateDiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).CalculateDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.marketing.v1.Marketing/CalculateDiscount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).CalculateDiscount(ctx, req.(*CalculateDiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_CreatePromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).CreatePromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.marketing.v1.Marketing/CreatePromotion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).CreatePromotion(ctx, req.(*CreatePromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_UpdatePromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).UpdatePromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.marketing.v1.Marketing/UpdatePromotion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).UpdatePromotion(ctx, req.(*UpdatePromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_DeletePromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).DeletePromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.marketing.v1.Marketing/DeletePromotion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).DeletePromotion(ctx, req.(*DeletePromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_GetPromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).GetPromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.marketing.v1.Marketing/GetPromotion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).GetPromotion(ctx, req.(*GetPromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_ListPromotions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPromotionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).ListPromotions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.marketing.v1.Marketing/ListPromotions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).ListPromotions(ctx, req.(*ListPromotionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Marketing_ServiceDesc is the grpc.ServiceDesc for Marketing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Marketing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.marketing.v1.Marketing",
	HandlerType: (*MarketingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCouponTemplate",
			Handler:    _Marketing_CreateCouponTemplate_Handler,
		},
		{
			MethodName: "ClaimCoupon",
			Handler:    _Marketing_ClaimCoupon_Handler,
		},
		{
			MethodName: "ListMyCoupons",
			Handler:    _Marketing_ListMyCoupons_Handler,
		},
		{
			MethodName: "CalculateDiscount",
			Handler:    _Marketing_CalculateDiscount_Handler,
		},
		{
			MethodName: "CreatePromotion",
			Handler:    _Marketing_CreatePromotion_Handler,
		},
		{
			MethodName: "UpdatePromotion",
			Handler:    _Marketing_UpdatePromotion_Handler,
		},
		{
			MethodName: "DeletePromotion",
			Handler:    _Marketing_DeletePromotion_Handler,
		},
		{
			MethodName: "GetPromotion",
			Handler:    _Marketing_GetPromotion_Handler,
		},
		{
			MethodName: "ListPromotions",
			Handler:    _Marketing_ListPromotions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/marketing/v1/marketing.proto",
}
