FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./ 
RUN go mod download

COPY . .

RUN go build -o /app/gateway ./cmd/gateway

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/gateway .
COPY configs/gateway.yaml ./configs/

EXPOSE 8000

CMD ["./gateway", "-conf", "./configs/gateway.yaml"]
