FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./ 
RUN go mod download

COPY . .

ARG SERVICE_NAME
RUN go build -o /app/${SERVICE_NAME} ./cmd/${SERVICE_NAME}

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/${SERVICE_NAME} .
COPY configs/${SERVICE_NAME}.yaml ./configs/

EXPOSE 9000 # Default gRPC port, override as needed

CMD ["./${SERVICE_NAME}", "-conf", "./configs/${SERVICE_NAME}.yaml"]
