// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/order/v1/order.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalAmount   uint64                 `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	PaymentAmount uint64                 `protobuf:"varint,4,opt,name=payment_amount,json=paymentAmount,proto3" json:"payment_amount,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"` // ... more fields
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_api_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderInfo) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderInfo) GetTotalAmount() uint64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *OrderInfo) GetPaymentAmount() uint64 {
	if x != nil {
		return x.PaymentAmount
	}
	return 0
}

func (x *OrderInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         uint64                 `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	ProductTitle  string                 `protobuf:"bytes,2,opt,name=product_title,json=productTitle,proto3" json:"product_title,omitempty"`
	ProductImage  string                 `protobuf:"bytes,3,opt,name=product_image,json=productImage,proto3" json:"product_image,omitempty"`
	Price         uint64                 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      uint32                 `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_api_order_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *OrderItem) GetProductTitle() string {
	if x != nil {
		return x.ProductTitle
	}
	return ""
}

func (x *OrderItem) GetProductImage() string {
	if x != nil {
		return x.ProductImage
	}
	return ""
}

func (x *OrderItem) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItem) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateOrderRequestItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         uint64                 `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequestItem) Reset() {
	*x = CreateOrderRequestItem{}
	mi := &file_api_order_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequestItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequestItem) ProtoMessage() {}

func (x *CreateOrderRequestItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequestItem.ProtoReflect.Descriptor instead.
func (*CreateOrderRequestItem) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderRequestItem) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CreateOrderRequestItem) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateOrderRequest struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	UserId          uint64                    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items           []*CreateOrderRequestItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	AddressId       uint64                    `protobuf:"varint,3,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`                  // 用户选择的收货地址ID
	Remark          string                    `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`                                          // 用户备注
	ShippingAddress []byte                    `protobuf:"bytes,5,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"` // 收货地址的 JSON 字符串
	PaymentAmount   uint64                    `protobuf:"varint,6,opt,name=payment_amount,json=paymentAmount,proto3" json:"payment_amount,omitempty"`      // 实际支付金额
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderRequest) GetItems() []*CreateOrderRequestItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateOrderRequest) GetAddressId() uint64 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

func (x *CreateOrderRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *CreateOrderRequest) GetShippingAddress() []byte {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *CreateOrderRequest) GetPaymentAmount() uint64 {
	if x != nil {
		return x.PaymentAmount
	}
	return 0
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_api_order_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrderResponse) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetOrderDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       uint64                 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailRequest) Reset() {
	*x = GetOrderDetailRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailRequest) ProtoMessage() {}

func (x *GetOrderDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailRequest.ProtoReflect.Descriptor instead.
func (*GetOrderDetailRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderDetailRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrderDetailRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetOrderDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderInfo             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailResponse) Reset() {
	*x = GetOrderDetailResponse{}
	mi := &file_api_order_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailResponse) ProtoMessage() {}

func (x *GetOrderDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailResponse.ProtoReflect.Descriptor instead.
func (*GetOrderDetailResponse) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderDetailResponse) GetOrder() *OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *GetOrderDetailResponse) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetPaymentURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       uint64                 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentURLRequest) Reset() {
	*x = GetPaymentURLRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentURLRequest) ProtoMessage() {}

func (x *GetPaymentURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentURLRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentURLRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{7}
}

func (x *GetPaymentURLRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPaymentURLRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetPaymentURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentUrl    string                 `protobuf:"bytes,1,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentURLResponse) Reset() {
	*x = GetPaymentURLResponse{}
	mi := &file_api_order_v1_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentURLResponse) ProtoMessage() {}

func (x *GetPaymentURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentURLResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentURLResponse) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{8}
}

func (x *GetPaymentURLResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

type ProcessPaymentNotificationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NotificationData map[string]string      `protobuf:"bytes,1,rep,name=notification_data,json=notificationData,proto3" json:"notification_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 接收支付宝POST的Form数据
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProcessPaymentNotificationRequest) Reset() {
	*x = ProcessPaymentNotificationRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentNotificationRequest) ProtoMessage() {}

func (x *ProcessPaymentNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentNotificationRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentNotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessPaymentNotificationRequest) GetNotificationData() map[string]string {
	if x != nil {
		return x.NotificationData
	}
	return nil
}

type ProcessPaymentNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentNotificationResponse) Reset() {
	*x = ProcessPaymentNotificationResponse{}
	mi := &file_api_order_v1_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentNotificationResponse) ProtoMessage() {}

func (x *ProcessPaymentNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentNotificationResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentNotificationResponse) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{10}
}

var File_api_order_v1_order_proto protoreflect.FileDescriptor

const file_api_order_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x18api/order/v1/order.proto\x12\fapi.order.v1\x1a\x1cgoogle/api/annotations.proto\"\xa1\x01\n" +
	"\tOrderInfo\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x04R\vtotalAmount\x12%\n" +
	"\x0epayment_amount\x18\x04 \x01(\x04R\rpaymentAmount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"\x9e\x01\n" +
	"\tOrderItem\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\x04R\x05skuId\x12#\n" +
	"\rproduct_title\x18\x02 \x01(\tR\fproductTitle\x12#\n" +
	"\rproduct_image\x18\x03 \x01(\tR\fproductImage\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x04R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\rR\bquantity\"K\n" +
	"\x16CreateOrderRequestItem\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\x04R\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\"\xf2\x01\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12:\n" +
	"\x05items\x18\x02 \x03(\v2$.api.order.v1.CreateOrderRequestItemR\x05items\x12\x1d\n" +
	"\n" +
	"address_id\x18\x03 \x01(\x04R\taddressId\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\x12)\n" +
	"\x10shipping_address\x18\x05 \x01(\fR\x0fshippingAddress\x12%\n" +
	"\x0epayment_amount\x18\x06 \x01(\x04R\rpaymentAmount\"0\n" +
	"\x13CreateOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\"K\n" +
	"\x15GetOrderDetailRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x04R\aorderId\"v\n" +
	"\x16GetOrderDetailResponse\x12-\n" +
	"\x05order\x18\x01 \x01(\v2\x17.api.order.v1.OrderInfoR\x05order\x12-\n" +
	"\x05items\x18\x02 \x03(\v2\x17.api.order.v1.OrderItemR\x05items\"J\n" +
	"\x14GetPaymentURLRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x04R\aorderId\"8\n" +
	"\x15GetPaymentURLResponse\x12\x1f\n" +
	"\vpayment_url\x18\x01 \x01(\tR\n" +
	"paymentUrl\"\xdc\x01\n" +
	"!ProcessPaymentNotificationRequest\x12r\n" +
	"\x11notification_data\x18\x01 \x03(\v2E.api.order.v1.ProcessPaymentNotificationRequest.NotificationDataEntryR\x10notificationData\x1aC\n" +
	"\x15NotificationDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"$\n" +
	"\"ProcessPaymentNotificationResponse2\xce\x03\n" +
	"\x05Order\x12i\n" +
	"\vCreateOrder\x12 .api.order.v1.CreateOrderRequest\x1a!.api.order.v1.CreateOrderResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/orders\x12z\n" +
	"\x0eGetOrderDetail\x12#.api.order.v1.GetOrderDetailRequest\x1a$.api.order.v1.GetOrderDetailResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/orders/{order_id}\x12Z\n" +
	"\rGetPaymentURL\x12\".api.order.v1.GetPaymentURLRequest\x1a#.api.order.v1.GetPaymentURLResponse\"\x00\x12\x81\x01\n" +
	"\x1aProcessPaymentNotification\x12/.api.order.v1.ProcessPaymentNotificationRequest\x1a0.api.order.v1.ProcessPaymentNotificationResponse\"\x00B\x1bZ\x19ecommerce/api/order/v1;v1b\x06proto3"

var (
	file_api_order_v1_order_proto_rawDescOnce sync.Once
	file_api_order_v1_order_proto_rawDescData []byte
)

func file_api_order_v1_order_proto_rawDescGZIP() []byte {
	file_api_order_v1_order_proto_rawDescOnce.Do(func() {
		file_api_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_order_v1_order_proto_rawDesc), len(file_api_order_v1_order_proto_rawDesc)))
	})
	return file_api_order_v1_order_proto_rawDescData
}

var file_api_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_order_v1_order_proto_goTypes = []any{
	(*OrderInfo)(nil),                          // 0: api.order.v1.OrderInfo
	(*OrderItem)(nil),                          // 1: api.order.v1.OrderItem
	(*CreateOrderRequestItem)(nil),             // 2: api.order.v1.CreateOrderRequestItem
	(*CreateOrderRequest)(nil),                 // 3: api.order.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),                // 4: api.order.v1.CreateOrderResponse
	(*GetOrderDetailRequest)(nil),              // 5: api.order.v1.GetOrderDetailRequest
	(*GetOrderDetailResponse)(nil),             // 6: api.order.v1.GetOrderDetailResponse
	(*GetPaymentURLRequest)(nil),               // 7: api.order.v1.GetPaymentURLRequest
	(*GetPaymentURLResponse)(nil),              // 8: api.order.v1.GetPaymentURLResponse
	(*ProcessPaymentNotificationRequest)(nil),  // 9: api.order.v1.ProcessPaymentNotificationRequest
	(*ProcessPaymentNotificationResponse)(nil), // 10: api.order.v1.ProcessPaymentNotificationResponse
	nil, // 11: api.order.v1.ProcessPaymentNotificationRequest.NotificationDataEntry
}
var file_api_order_v1_order_proto_depIdxs = []int32{
	2,  // 0: api.order.v1.CreateOrderRequest.items:type_name -> api.order.v1.CreateOrderRequestItem
	0,  // 1: api.order.v1.GetOrderDetailResponse.order:type_name -> api.order.v1.OrderInfo
	1,  // 2: api.order.v1.GetOrderDetailResponse.items:type_name -> api.order.v1.OrderItem
	11, // 3: api.order.v1.ProcessPaymentNotificationRequest.notification_data:type_name -> api.order.v1.ProcessPaymentNotificationRequest.NotificationDataEntry
	3,  // 4: api.order.v1.Order.CreateOrder:input_type -> api.order.v1.CreateOrderRequest
	5,  // 5: api.order.v1.Order.GetOrderDetail:input_type -> api.order.v1.GetOrderDetailRequest
	7,  // 6: api.order.v1.Order.GetPaymentURL:input_type -> api.order.v1.GetPaymentURLRequest
	9,  // 7: api.order.v1.Order.ProcessPaymentNotification:input_type -> api.order.v1.ProcessPaymentNotificationRequest
	4,  // 8: api.order.v1.Order.CreateOrder:output_type -> api.order.v1.CreateOrderResponse
	6,  // 9: api.order.v1.Order.GetOrderDetail:output_type -> api.order.v1.GetOrderDetailResponse
	8,  // 10: api.order.v1.Order.GetPaymentURL:output_type -> api.order.v1.GetPaymentURLResponse
	10, // 11: api.order.v1.Order.ProcessPaymentNotification:output_type -> api.order.v1.ProcessPaymentNotificationResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_order_v1_order_proto_init() }
func file_api_order_v1_order_proto_init() {
	if File_api_order_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_order_v1_order_proto_rawDesc), len(file_api_order_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_order_v1_order_proto_goTypes,
		DependencyIndexes: file_api_order_v1_order_proto_depIdxs,
		MessageInfos:      file_api_order_v1_order_proto_msgTypes,
	}.Build()
	File_api_order_v1_order_proto = out.File
	file_api_order_v1_order_proto_goTypes = nil
	file_api_order_v1_order_proto_depIdxs = nil
}
