apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "wallet.fullname" . }}
  labels:
    {{- include "wallet.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "wallet.selectorLabels" . | nindent 6 }}