// Package application 统一身份认证应用服务
package application

import (
	"context"
	"errors"
	"log/slog"
	"time"

	"github.com/wyfcoding/ecommerce/internal/iam/domain"
	"github.com/wyfcoding/pkg/jwt"
	"github.com/wyfcoding/pkg/security"
)

// AuthService 认证服务
type AuthService struct {
	credRepo  domain.CredentialRepository
	roleRepo  domain.RoleRepository
	logRepo   domain.AuthLogRepository
	jwtConfig JWTConfig
	logger    *slog.Logger
}

type JWTConfig struct {
	Secret         string
	Issuer         string
	ExpireDuration time.Duration
}

func NewAuthService(
	credRepo domain.CredentialRepository,
	roleRepo domain.RoleRepository,
	logRepo domain.AuthLogRepository,
	jwtConfig JWTConfig,
	logger *slog.Logger,
) *AuthService {
	return &AuthService{
		credRepo:  credRepo,
		roleRepo:  roleRepo,
		logRepo:   logRepo,
		jwtConfig: jwtConfig,
		logger:    logger.With("module", "iam_service"),
	}
}

// Login 登录并颁发 Token
func (s *AuthService) Login(ctx context.Context, username, password, ip, ua string) (string, error) {
	cred, err := s.credRepo.GetByUsername(ctx, username)
	if err != nil {
		s.logAuth(ctx, username, ip, ua, "LOGIN", "FAILED", "user_not_found")
		return "", errors.New("invalid credentials")
	}

	if !security.CheckPassword(password, cred.PasswordHash) {
		s.logAuth(ctx, cred.SubjectID, ip, ua, "LOGIN", "FAILED", "password_mismatch")
		return "", errors.New("invalid credentials")
	}

	if cred.Status == 0 {
		return "", errors.New("account disabled")
	}

	// 获取角色
	roles, err := s.roleRepo.GetBySubjectID(ctx, cred.SubjectID)
	if err != nil {
		s.logger.WarnContext(ctx, "failed to get roles", "subject_id", cred.SubjectID, "error", err)
		// 不阻断登录
	}

	// 生成 Token
	// Convert SubjectID (string) to uint64 if possible, or use 0 and store string in extra claims
	// 假设 pkg/jwt.GenerateToken 仅接受 uint64 userID，这里可能需要适配。
	// 为保持一致性，假设 SubjectID 是数字型字符串，或者我们只把这个Token作为 Bearer。
	// 这里演示适配：假设 SubjectID 可以转为 uint64，或者修改 pkg/jwt 支持 string Subject。
	// *Critical*: pkg/jwt signature is `GenerateToken(userID uint64, ...)`
	// 我们需要确保 SubjectID 是数字，或者我们在这个项目里约定 SubjectID 就是 UserID。

	// 这里简化处理：假定 SubjectID 是数字字符串
	// 实际项目中应增强 pkg/jwt 支持 string ID
	userID := uint64(0) // dynamic parse if needed

	token, err := jwt.GenerateToken(userID, cred.Username, roles, s.jwtConfig.Secret, s.jwtConfig.Issuer, s.jwtConfig.ExpireDuration)
	if err != nil {
		return "", err
	}

	// 更新登录时间
	now := time.Now()
	cred.LastLoginAt = &now
	_ = s.credRepo.Update(ctx, cred)

	s.logAuth(ctx, cred.SubjectID, ip, ua, "LOGIN", "SUCCESS", "")
	return token, nil
}

// Register 注册新用户
func (s *AuthService) Register(ctx context.Context, req RegisterCmd) error {
	hash, err := security.HashPassword(req.Password)
	if err != nil {
		return err
	}

	cred := &domain.Credential{
		SubjectID:    req.SubjectID, // Usually generated by external service (User/Merchant) or IDGen
		SubjectType:  req.SubjectType,
		Username:     req.Username,
		PasswordHash: hash,
		Email:        req.Email,
		Phone:        req.Phone,
		Status:       1,
		TenantID:     req.TenantID,
	}

	return s.credRepo.Save(ctx, cred)
}

// ValidateToken 校验 Token (Introspect)
func (s *AuthService) ValidateToken(ctx context.Context, token string) (*jwt.MyCustomClaims, error) {
	return jwt.ParseToken(token, s.jwtConfig.Secret)
}

type RegisterCmd struct {
	SubjectID   string
	SubjectType domain.SubjectType
	Username    string
	Password    string
	Email       string
	Phone       string
	TenantID    string
}

func (s *AuthService) logAuth(ctx context.Context, subjectID, ip, ua, action, result, reason string) {
	_ = s.logRepo.Save(ctx, &domain.AuthLog{
		SubjectID: subjectID,
		ClientIP:  ip,
		UserAgent: ua,
		Action:    action,
		Result:    result,
		Reason:    reason,
	})
}
