// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: ecommerce/api/search/v1/search.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpuId         uint64                 `protobuf:"varint,1,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	SubTitle      string                 `protobuf:"bytes,3,opt,name=sub_title,json=subTitle,proto3" json:"sub_title,omitempty"`
	MainImage     string                 `protobuf:"bytes,4,opt,name=main_image,json=mainImage,proto3" json:"main_image,omitempty"`
	Price         uint64                 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"` // ... 其他需要在搜索結果頁展示的字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductHit) Reset() {
	*x = ProductHit{}
	mi := &file_ecommerce_api_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductHit) ProtoMessage() {}

func (x *ProductHit) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductHit.ProtoReflect.Descriptor instead.
func (*ProductHit) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *ProductHit) GetSpuId() uint64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *ProductHit) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProductHit) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *ProductHit) GetMainImage() string {
	if x != nil {
		return x.MainImage
	}
	return ""
}

func (x *ProductHit) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type SearchProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	CategoryId    *uint64                `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	BrandId       *uint64                `protobuf:"varint,3,opt,name=brand_id,json=brandId,proto3,oneof" json:"brand_id,omitempty"`
	SortBy        string                 `protobuf:"bytes,4,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"` // e.g. "relevance", "price_asc", "price_desc"
	Page          uint32                 `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsRequest) Reset() {
	*x = SearchProductsRequest{}
	mi := &file_ecommerce_api_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsRequest) ProtoMessage() {}

func (x *SearchProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsRequest.ProtoReflect.Descriptor instead.
func (*SearchProductsRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchProductsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchProductsRequest) GetCategoryId() uint64 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *SearchProductsRequest) GetBrandId() uint64 {
	if x != nil && x.BrandId != nil {
		return *x.BrandId
	}
	return 0
}

func (x *SearchProductsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *SearchProductsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchProductsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*ProductHit          `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // Facets/Aggregations can be added here in the future
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsResponse) Reset() {
	*x = SearchProductsResponse{}
	mi := &file_ecommerce_api_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsResponse) ProtoMessage() {}

func (x *SearchProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsResponse.ProtoReflect.Descriptor instead.
func (*SearchProductsResponse) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchProductsResponse) GetHits() []*ProductHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *SearchProductsResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_ecommerce_api_search_v1_search_proto protoreflect.FileDescriptor

const file_ecommerce_api_search_v1_search_proto_rawDesc = "" +
	"\n" +
	"$ecommerce/api/search/v1/search.proto\x12\rapi.search.v1\x1a\x1cgoogle/api/annotations.proto\"\x8b\x01\n" +
	"\n" +
	"ProductHit\x12\x15\n" +
	"\x06spu_id\x18\x01 \x01(\x04R\x05spuId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tsub_title\x18\x03 \x01(\tR\bsubTitle\x12\x1d\n" +
	"\n" +
	"main_image\x18\x04 \x01(\tR\tmainImage\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x04R\x05price\"\xde\x01\n" +
	"\x15SearchProductsRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12$\n" +
	"\vcategory_id\x18\x02 \x01(\x04H\x00R\n" +
	"categoryId\x88\x01\x01\x12\x1e\n" +
	"\bbrand_id\x18\x03 \x01(\x04H\x01R\abrandId\x88\x01\x01\x12\x17\n" +
	"\asort_by\x18\x04 \x01(\tR\x06sortBy\x12\x12\n" +
	"\x04page\x18\x05 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\rR\bpageSizeB\x0e\n" +
	"\f_category_idB\v\n" +
	"\t_brand_id\"]\n" +
	"\x16SearchProductsResponse\x12-\n" +
	"\x04hits\x18\x01 \x03(\v2\x19.api.search.v1.ProductHitR\x04hits\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total2\x84\x01\n" +
	"\x06Search\x12z\n" +
	"\x0eSearchProducts\x12$.api.search.v1.SearchProductsRequest\x1a%.api.search.v1.SearchProductsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/search/productsB&Z$ecommerce/ecommerce/api/search/v1;v1b\x06proto3"

var (
	file_ecommerce_api_search_v1_search_proto_rawDescOnce sync.Once
	file_ecommerce_api_search_v1_search_proto_rawDescData []byte
)

func file_ecommerce_api_search_v1_search_proto_rawDescGZIP() []byte {
	file_ecommerce_api_search_v1_search_proto_rawDescOnce.Do(func() {
		file_ecommerce_api_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ecommerce_api_search_v1_search_proto_rawDesc), len(file_ecommerce_api_search_v1_search_proto_rawDesc)))
	})
	return file_ecommerce_api_search_v1_search_proto_rawDescData
}

var file_ecommerce_api_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ecommerce_api_search_v1_search_proto_goTypes = []any{
	(*ProductHit)(nil),             // 0: api.search.v1.ProductHit
	(*SearchProductsRequest)(nil),  // 1: api.search.v1.SearchProductsRequest
	(*SearchProductsResponse)(nil), // 2: api.search.v1.SearchProductsResponse
}
var file_ecommerce_api_search_v1_search_proto_depIdxs = []int32{
	0, // 0: api.search.v1.SearchProductsResponse.hits:type_name -> api.search.v1.ProductHit
	1, // 1: api.search.v1.Search.SearchProducts:input_type -> api.search.v1.SearchProductsRequest
	2, // 2: api.search.v1.Search.SearchProducts:output_type -> api.search.v1.SearchProductsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ecommerce_api_search_v1_search_proto_init() }
func file_ecommerce_api_search_v1_search_proto_init() {
	if File_ecommerce_api_search_v1_search_proto != nil {
		return
	}
	file_ecommerce_api_search_v1_search_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ecommerce_api_search_v1_search_proto_rawDesc), len(file_ecommerce_api_search_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ecommerce_api_search_v1_search_proto_goTypes,
		DependencyIndexes: file_ecommerce_api_search_v1_search_proto_depIdxs,
		MessageInfos:      file_ecommerce_api_search_v1_search_proto_msgTypes,
	}.Build()
	File_ecommerce_api_search_v1_search_proto = out.File
	file_ecommerce_api_search_v1_search_proto_goTypes = nil
	file_ecommerce_api_search_v1_search_proto_depIdxs = nil
}
