[service]
name = "orchestrator"
version = "v1.0.0"

[server]
grpc_port = 50062

[database]
driver = "mysql"
dsn = "root:root1234@tcp(127.0.0.1:3306)/ecommerce?charset=utf8mb4&parseTime=True&loc=Local"

[log]
level = "info"
format = "json"

[saga]
# 事务重试次数
max_retries = 3
# 步骤超时时间 (s)
step_timeout_seconds = 60
