apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: user-service
  namespace: ecommerce
spec:
  hosts:
  - user-service
  - api.ecommerce.com
  gateways:
  - ecommerce-gateway
  - mesh
  http:
  # 金丝雀发布：10% 流量到 v2
  - match:
    - uri:
        prefix: /api/v1/users
    route:
    - destination:
        host: user-service
        subset: v1
      weight: 90
    - destination:
        host: user-service
        subset: v2
      weight: 10
    timeout: 30s
    retries:
      attempts: 3
      perTryTimeout: 10s
      retryOn: 5xx,reset,connect-failure,refused-stream
    fault:
      delay:
        percentage:
          value: 0.1
        fixedDelay: 5s
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: product-service
  namespace: ecommerce
spec:
  hosts:
  - product-service
  - api.ecommerce.com
  gateways:
  - ecommerce-gateway
  - mesh
  http:
  - match:
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: product-service
        subset: v1
      weight: 100
    timeout: 30s
    retries:
      attempts: 3
      perTryTimeout: 10s
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: order-service
  namespace: ecommerce
spec:
  hosts:
  - order-service
  - api.ecommerce.com
  gateways:
  - ecommerce-gateway
  - mesh
  http:
  - match:
    - uri:
        prefix: /api/v1/orders
    route:
    - destination:
        host: order-service
        subset: v1
      weight: 100
    timeout: 60s
    retries:
      attempts: 2
      perTryTimeout: 30s
