# Build stage
FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o kyc ecommerce/cmd/kyc/main.go

# Run stage
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/kyc .
COPY --from=builder /app/ecommerce/configs/kyc/config.toml ./configs/

EXPOSE 50063

CMD ["./kyc"]
