replicaCount: 1

image:
  repository: recommendation
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: true

service:
  type: ClusterIP
  httpPort: 8080
  grpcPort: 9090

resources: 
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

env:
  - name: ECOMMERCE_SERVER_HTTP_PORT
    value: "8080"
  - name: ECOMMERCE_SERVER_GRPC_PORT
    value: "9090"
  - name: ML_MODEL_PATH
    value: "/models"

secrets:
  dbPassword: ""
  redisPassword: ""
  mlflowTrackingUri: ""

volumes:
  models:
    enabled: true
    size: 5Gi
    storageClass: ""
