// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: ecommerce/api/product/v1/product.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Product_ListCategories_FullMethodName = "/api.product.v1.Product/ListCategories"
	Product_GetSpuDetail_FullMethodName   = "/api.product.v1.Product/GetSpuDetail"
	Product_GetSkuInfos_FullMethodName    = "/api.product.v1.Product/GetSkuInfos"
	Product_LockStock_FullMethodName      = "/api.product.v1.Product/LockStock"
)

// ProductClient is the client API for Product service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 商品服务
type ProductClient interface {
	// 获取商品分类列表
	ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error)
	// 获取SPU商品详情
	GetSpuDetail(ctx context.Context, in *GetSpuDetailRequest, opts ...grpc.CallOption) (*GetSpuDetailResponse, error)
	// 批量获取 SKU 信息 (为订单服务等内部调用准备)
	GetSkuInfos(ctx context.Context, in *GetSkuInfosRequest, opts ...grpc.CallOption) (*GetSkuInfosResponse, error)
	// 锁定库存 (为订单服务准备)
	LockStock(ctx context.Context, in *LockStockRequest, opts ...grpc.CallOption) (*LockStockResponse, error)
}

type productClient struct {
	cc grpc.ClientConnInterface
}

func NewProductClient(cc grpc.ClientConnInterface) ProductClient {
	return &productClient{cc}
}

func (c *productClient) ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCategoriesResponse)
	err := c.cc.Invoke(ctx, Product_ListCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) GetSpuDetail(ctx context.Context, in *GetSpuDetailRequest, opts ...grpc.CallOption) (*GetSpuDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSpuDetailResponse)
	err := c.cc.Invoke(ctx, Product_GetSpuDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) GetSkuInfos(ctx context.Context, in *GetSkuInfosRequest, opts ...grpc.CallOption) (*GetSkuInfosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSkuInfosResponse)
	err := c.cc.Invoke(ctx, Product_GetSkuInfos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) LockStock(ctx context.Context, in *LockStockRequest, opts ...grpc.CallOption) (*LockStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockStockResponse)
	err := c.cc.Invoke(ctx, Product_LockStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServer is the server API for Product service.
// All implementations must embed UnimplementedProductServer
// for forward compatibility.
//
// 商品服务
type ProductServer interface {
	// 获取商品分类列表
	ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error)
	// 获取SPU商品详情
	GetSpuDetail(context.Context, *GetSpuDetailRequest) (*GetSpuDetailResponse, error)
	// 批量获取 SKU 信息 (为订单服务等内部调用准备)
	GetSkuInfos(context.Context, *GetSkuInfosRequest) (*GetSkuInfosResponse, error)
	// 锁定库存 (为订单服务准备)
	LockStock(context.Context, *LockStockRequest) (*LockStockResponse, error)
	mustEmbedUnimplementedProductServer()
}

// UnimplementedProductServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductServer struct{}

func (UnimplementedProductServer) ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCategories not implemented")
}
func (UnimplementedProductServer) GetSpuDetail(context.Context, *GetSpuDetailRequest) (*GetSpuDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpuDetail not implemented")
}
func (UnimplementedProductServer) GetSkuInfos(context.Context, *GetSkuInfosRequest) (*GetSkuInfosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSkuInfos not implemented")
}
func (UnimplementedProductServer) LockStock(context.Context, *LockStockRequest) (*LockStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockStock not implemented")
}
func (UnimplementedProductServer) mustEmbedUnimplementedProductServer() {}
func (UnimplementedProductServer) testEmbeddedByValue()                 {}

// UnsafeProductServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServer will
// result in compilation errors.
type UnsafeProductServer interface {
	mustEmbedUnimplementedProductServer()
}

func RegisterProductServer(s grpc.ServiceRegistrar, srv ProductServer) {
	// If the following call pancis, it indicates UnimplementedProductServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Product_ServiceDesc, srv)
}

func _Product_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_ListCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).ListCategories(ctx, req.(*ListCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_GetSpuDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpuDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).GetSpuDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_GetSpuDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).GetSpuDetail(ctx, req.(*GetSpuDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_GetSkuInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkuInfosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).GetSkuInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_GetSkuInfos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).GetSkuInfos(ctx, req.(*GetSkuInfosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_LockStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).LockStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_LockStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).LockStock(ctx, req.(*LockStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Product_ServiceDesc is the grpc.ServiceDesc for Product service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Product_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.product.v1.Product",
	HandlerType: (*ProductServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCategories",
			Handler:    _Product_ListCategories_Handler,
		},
		{
			MethodName: "GetSpuDetail",
			Handler:    _Product_GetSpuDetail_Handler,
		},
		{
			MethodName: "GetSkuInfos",
			Handler:    _Product_GetSkuInfos_Handler,
		},
		{
			MethodName: "LockStock",
			Handler:    _Product_LockStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ecommerce/api/product/v1/product.proto",
}
