// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: ecommerce/api/product/v1/product.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 商品分类信息
type CategoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      uint64                 `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Level         uint32                 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	SortOrder     uint32                 `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	IsVisible     bool                   `protobuf:"varint,7,opt,name=is_visible,json=isVisible,proto3" json:"is_visible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryInfo) Reset() {
	*x = CategoryInfo{}
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInfo) ProtoMessage() {}

func (x *CategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInfo.ProtoReflect.Descriptor instead.
func (*CategoryInfo) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_product_v1_product_proto_rawDescGZIP(), []int{0}
}

func (x *CategoryInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryInfo) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CategoryInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryInfo) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CategoryInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CategoryInfo) GetSortOrder() uint32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *CategoryInfo) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

// 商品SPU信息
type SpuInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpuId         uint64                 `protobuf:"varint,1,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	CategoryId    uint64                 `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	BrandId       uint64                 `protobuf:"varint,3,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	SubTitle      string                 `protobuf:"bytes,5,opt,name=sub_title,json=subTitle,proto3" json:"sub_title,omitempty"`
	MainImage     string                 `protobuf:"bytes,6,opt,name=main_image,json=mainImage,proto3" json:"main_image,omitempty"`
	GalleryImages []string               `protobuf:"bytes,7,rep,name=gallery_images,json=galleryImages,proto3" json:"gallery_images,omitempty"`
	DetailHtml    string                 `protobuf:"bytes,8,opt,name=detail_html,json=detailHtml,proto3" json:"detail_html,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpuInfo) Reset() {
	*x = SpuInfo{}
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpuInfo) ProtoMessage() {}

func (x *SpuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpuInfo.ProtoReflect.Descriptor instead.
func (*SpuInfo) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_product_v1_product_proto_rawDescGZIP(), []int{1}
}

func (x *SpuInfo) GetSpuId() uint64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *SpuInfo) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *SpuInfo) GetBrandId() uint64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *SpuInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SpuInfo) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *SpuInfo) GetMainImage() string {
	if x != nil {
		return x.MainImage
	}
	return ""
}

func (x *SpuInfo) GetGalleryImages() []string {
	if x != nil {
		return x.GalleryImages
	}
	return nil
}

func (x *SpuInfo) GetDetailHtml() string {
	if x != nil {
		return x.DetailHtml
	}
	return ""
}

func (x *SpuInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 商品SKU信息
type SkuInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         uint64                 `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	SpuId         uint64                 `protobuf:"varint,2,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Price         uint64                 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`                                      // 价格, 单位: 分
	OriginalPrice uint64                 `protobuf:"varint,5,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"` // 原价, 单位: 分
	Stock         uint32                 `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	Image         string                 `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	Specs         map[string]string      `protobuf:"bytes,8,rep,name=specs,proto3" json:"specs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 规格, e.g. {"颜色": "黑色", "容量": "256GB"}
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkuInfo) Reset() {
	*x = SkuInfo{}
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuInfo) ProtoMessage() {}

func (x *SkuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuInfo.ProtoReflect.Descriptor instead.
func (*SkuInfo) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_product_v1_product_proto_rawDescGZIP(), []int{2}
}

func (x *SkuInfo) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *SkuInfo) GetSpuId() uint64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *SkuInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SkuInfo) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SkuInfo) GetOriginalPrice() uint64 {
	if x != nil {
		return x.OriginalPrice
	}
	return 0
}

func (x *SkuInfo) GetStock() uint32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *SkuInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SkuInfo) GetSpecs() map[string]string {
	if x != nil {
		return x.Specs
	}
	return nil
}

func (x *SkuInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 获取商品分类列表请求
type ListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      uint64                 `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // 父分类ID, 0表示获取顶级分类
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_product_v1_product_proto_rawDescGZIP(), []int{3}
}

func (x *ListCategoriesRequest) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

// 获取商品分类列表响应
type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*CategoryInfo        `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_product_v1_product_proto_rawDescGZIP(), []int{4}
}

func (x *ListCategoriesResponse) GetCategories() []*CategoryInfo {
	if x != nil {
		return x.Categories
	}
	return nil
}

// 获取SPU商品详情请求
type GetSpuDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpuId         uint64                 `protobuf:"varint,1,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpuDetailRequest) Reset() {
	*x = GetSpuDetailRequest{}
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpuDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpuDetailRequest) ProtoMessage() {}

func (x *GetSpuDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpuDetailRequest.ProtoReflect.Descriptor instead.
func (*GetSpuDetailRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_product_v1_product_proto_rawDescGZIP(), []int{5}
}

func (x *GetSpuDetailRequest) GetSpuId() uint64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

// 获取SPU商品详情响应
type GetSpuDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spu           *SpuInfo               `protobuf:"bytes,1,opt,name=spu,proto3" json:"spu,omitempty"`
	Skus          []*SkuInfo             `protobuf:"bytes,2,rep,name=skus,proto3" json:"skus,omitempty"` // 包含该SPU下的所有SKU
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpuDetailResponse) Reset() {
	*x = GetSpuDetailResponse{}
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpuDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpuDetailResponse) ProtoMessage() {}

func (x *GetSpuDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpuDetailResponse.ProtoReflect.Descriptor instead.
func (*GetSpuDetailResponse) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_product_v1_product_proto_rawDescGZIP(), []int{6}
}

func (x *GetSpuDetailResponse) GetSpu() *SpuInfo {
	if x != nil {
		return x.Spu
	}
	return nil
}

func (x *GetSpuDetailResponse) GetSkus() []*SkuInfo {
	if x != nil {
		return x.Skus
	}
	return nil
}

type GetSkuInfosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuIds        []uint64               `protobuf:"varint,1,rep,packed,name=sku_ids,json=skuIds,proto3" json:"sku_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkuInfosRequest) Reset() {
	*x = GetSkuInfosRequest{}
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkuInfosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkuInfosRequest) ProtoMessage() {}

func (x *GetSkuInfosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkuInfosRequest.ProtoReflect.Descriptor instead.
func (*GetSkuInfosRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_product_v1_product_proto_rawDescGZIP(), []int{7}
}

func (x *GetSkuInfosRequest) GetSkuIds() []uint64 {
	if x != nil {
		return x.SkuIds
	}
	return nil
}

type GetSkuInfosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skus          []*SkuInfo             `protobuf:"bytes,1,rep,name=skus,proto3" json:"skus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkuInfosResponse) Reset() {
	*x = GetSkuInfosResponse{}
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkuInfosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkuInfosResponse) ProtoMessage() {}

func (x *GetSkuInfosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkuInfosResponse.ProtoReflect.Descriptor instead.
func (*GetSkuInfosResponse) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_product_v1_product_proto_rawDescGZIP(), []int{8}
}

func (x *GetSkuInfosResponse) GetSkus() []*SkuInfo {
	if x != nil {
		return x.Skus
	}
	return nil
}

type LockStockItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         uint64                 `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockStockItem) Reset() {
	*x = LockStockItem{}
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockStockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockStockItem) ProtoMessage() {}

func (x *LockStockItem) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockStockItem.ProtoReflect.Descriptor instead.
func (*LockStockItem) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_product_v1_product_proto_rawDescGZIP(), []int{9}
}

func (x *LockStockItem) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *LockStockItem) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type LockStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*LockStockItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockStockRequest) Reset() {
	*x = LockStockRequest{}
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockStockRequest) ProtoMessage() {}

func (x *LockStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockStockRequest.ProtoReflect.Descriptor instead.
func (*LockStockRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_product_v1_product_proto_rawDescGZIP(), []int{10}
}

func (x *LockStockRequest) GetItems() []*LockStockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type LockStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockStockResponse) Reset() {
	*x = LockStockResponse{}
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockStockResponse) ProtoMessage() {}

func (x *LockStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_api_product_v1_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockStockResponse.ProtoReflect.Descriptor instead.
func (*LockStockResponse) Descriptor() ([]byte, []int) {
	return file_ecommerce_api_product_v1_product_proto_rawDescGZIP(), []int{11}
}

var File_ecommerce_api_product_v1_product_proto protoreflect.FileDescriptor

const file_ecommerce_api_product_v1_product_proto_rawDesc = "" +
	"\n" +
	"&ecommerce/api/product/v1/product.proto\x12\x0eapi.product.v1\x1a\x1cgoogle/api/annotations.proto\"\xb7\x01\n" +
	"\fCategoryInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x04R\bparentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x04 \x01(\rR\x05level\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\rR\tsortOrder\x12\x1d\n" +
	"\n" +
	"is_visible\x18\a \x01(\bR\tisVisible\"\x8e\x02\n" +
	"\aSpuInfo\x12\x15\n" +
	"\x06spu_id\x18\x01 \x01(\x04R\x05spuId\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x04R\n" +
	"categoryId\x12\x19\n" +
	"\bbrand_id\x18\x03 \x01(\x04R\abrandId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1b\n" +
	"\tsub_title\x18\x05 \x01(\tR\bsubTitle\x12\x1d\n" +
	"\n" +
	"main_image\x18\x06 \x01(\tR\tmainImage\x12%\n" +
	"\x0egallery_images\x18\a \x03(\tR\rgalleryImages\x12\x1f\n" +
	"\vdetail_html\x18\b \x01(\tR\n" +
	"detailHtml\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\"\xc2\x02\n" +
	"\aSkuInfo\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\x04R\x05skuId\x12\x15\n" +
	"\x06spu_id\x18\x02 \x01(\x04R\x05spuId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x04R\x05price\x12%\n" +
	"\x0eoriginal_price\x18\x05 \x01(\x04R\roriginalPrice\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\rR\x05stock\x12\x14\n" +
	"\x05image\x18\a \x01(\tR\x05image\x128\n" +
	"\x05specs\x18\b \x03(\v2\".api.product.v1.SkuInfo.SpecsEntryR\x05specs\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x1a8\n" +
	"\n" +
	"SpecsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x15ListCategoriesRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\x04R\bparentId\"V\n" +
	"\x16ListCategoriesResponse\x12<\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x1c.api.product.v1.CategoryInfoR\n" +
	"categories\",\n" +
	"\x13GetSpuDetailRequest\x12\x15\n" +
	"\x06spu_id\x18\x01 \x01(\x04R\x05spuId\"n\n" +
	"\x14GetSpuDetailResponse\x12)\n" +
	"\x03spu\x18\x01 \x01(\v2\x17.api.product.v1.SpuInfoR\x03spu\x12+\n" +
	"\x04skus\x18\x02 \x03(\v2\x17.api.product.v1.SkuInfoR\x04skus\"-\n" +
	"\x12GetSkuInfosRequest\x12\x17\n" +
	"\asku_ids\x18\x01 \x03(\x04R\x06skuIds\"B\n" +
	"\x13GetSkuInfosResponse\x12+\n" +
	"\x04skus\x18\x01 \x03(\v2\x17.api.product.v1.SkuInfoR\x04skus\"B\n" +
	"\rLockStockItem\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\x04R\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\"G\n" +
	"\x10LockStockRequest\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.api.product.v1.LockStockItemR\x05items\"\x13\n" +
	"\x11LockStockResponse2\xae\x03\n" +
	"\aProduct\x12w\n" +
	"\x0eListCategories\x12%.api.product.v1.ListCategoriesRequest\x1a&.api.product.v1.ListCategoriesResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/categories\x12|\n" +
	"\fGetSpuDetail\x12#.api.product.v1.GetSpuDetailRequest\x1a$.api.product.v1.GetSpuDetailResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/products/spu/{spu_id}\x12X\n" +
	"\vGetSkuInfos\x12\".api.product.v1.GetSkuInfosRequest\x1a#.api.product.v1.GetSkuInfosResponse\"\x00\x12R\n" +
	"\tLockStock\x12 .api.product.v1.LockStockRequest\x1a!.api.product.v1.LockStockResponse\"\x00B'Z%ecommerce/ecommerce/api/product/v1;v1b\x06proto3"

var (
	file_ecommerce_api_product_v1_product_proto_rawDescOnce sync.Once
	file_ecommerce_api_product_v1_product_proto_rawDescData []byte
)

func file_ecommerce_api_product_v1_product_proto_rawDescGZIP() []byte {
	file_ecommerce_api_product_v1_product_proto_rawDescOnce.Do(func() {
		file_ecommerce_api_product_v1_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ecommerce_api_product_v1_product_proto_rawDesc), len(file_ecommerce_api_product_v1_product_proto_rawDesc)))
	})
	return file_ecommerce_api_product_v1_product_proto_rawDescData
}

var file_ecommerce_api_product_v1_product_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_ecommerce_api_product_v1_product_proto_goTypes = []any{
	(*CategoryInfo)(nil),           // 0: api.product.v1.CategoryInfo
	(*SpuInfo)(nil),                // 1: api.product.v1.SpuInfo
	(*SkuInfo)(nil),                // 2: api.product.v1.SkuInfo
	(*ListCategoriesRequest)(nil),  // 3: api.product.v1.ListCategoriesRequest
	(*ListCategoriesResponse)(nil), // 4: api.product.v1.ListCategoriesResponse
	(*GetSpuDetailRequest)(nil),    // 5: api.product.v1.GetSpuDetailRequest
	(*GetSpuDetailResponse)(nil),   // 6: api.product.v1.GetSpuDetailResponse
	(*GetSkuInfosRequest)(nil),     // 7: api.product.v1.GetSkuInfosRequest
	(*GetSkuInfosResponse)(nil),    // 8: api.product.v1.GetSkuInfosResponse
	(*LockStockItem)(nil),          // 9: api.product.v1.LockStockItem
	(*LockStockRequest)(nil),       // 10: api.product.v1.LockStockRequest
	(*LockStockResponse)(nil),      // 11: api.product.v1.LockStockResponse
	nil,                            // 12: api.product.v1.SkuInfo.SpecsEntry
}
var file_ecommerce_api_product_v1_product_proto_depIdxs = []int32{
	12, // 0: api.product.v1.SkuInfo.specs:type_name -> api.product.v1.SkuInfo.SpecsEntry
	0,  // 1: api.product.v1.ListCategoriesResponse.categories:type_name -> api.product.v1.CategoryInfo
	1,  // 2: api.product.v1.GetSpuDetailResponse.spu:type_name -> api.product.v1.SpuInfo
	2,  // 3: api.product.v1.GetSpuDetailResponse.skus:type_name -> api.product.v1.SkuInfo
	2,  // 4: api.product.v1.GetSkuInfosResponse.skus:type_name -> api.product.v1.SkuInfo
	9,  // 5: api.product.v1.LockStockRequest.items:type_name -> api.product.v1.LockStockItem
	3,  // 6: api.product.v1.Product.ListCategories:input_type -> api.product.v1.ListCategoriesRequest
	5,  // 7: api.product.v1.Product.GetSpuDetail:input_type -> api.product.v1.GetSpuDetailRequest
	7,  // 8: api.product.v1.Product.GetSkuInfos:input_type -> api.product.v1.GetSkuInfosRequest
	10, // 9: api.product.v1.Product.LockStock:input_type -> api.product.v1.LockStockRequest
	4,  // 10: api.product.v1.Product.ListCategories:output_type -> api.product.v1.ListCategoriesResponse
	6,  // 11: api.product.v1.Product.GetSpuDetail:output_type -> api.product.v1.GetSpuDetailResponse
	8,  // 12: api.product.v1.Product.GetSkuInfos:output_type -> api.product.v1.GetSkuInfosResponse
	11, // 13: api.product.v1.Product.LockStock:output_type -> api.product.v1.LockStockResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_ecommerce_api_product_v1_product_proto_init() }
func file_ecommerce_api_product_v1_product_proto_init() {
	if File_ecommerce_api_product_v1_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ecommerce_api_product_v1_product_proto_rawDesc), len(file_ecommerce_api_product_v1_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ecommerce_api_product_v1_product_proto_goTypes,
		DependencyIndexes: file_ecommerce_api_product_v1_product_proto_depIdxs,
		MessageInfos:      file_ecommerce_api_product_v1_product_proto_msgTypes,
	}.Build()
	File_ecommerce_api_product_v1_product_proto = out.File
	file_ecommerce_api_product_v1_product_proto_goTypes = nil
	file_ecommerce_api_product_v1_product_proto_depIdxs = nil
}
